name: Check pull request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:

  test:
    name: Test
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout the source
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Setup dependency cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Ensure dependencies are downloaded
        run: go mod download
      - name: Setup Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.11.0
      - name: Run the tests
        run: make test

  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: Ensure dependencies are downloaded
        run: go mod download
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          skip-cache: true